### ISSUE TITLE
logo to link it in readme

### ISSUE THREAD

**Issue by makus82** [Skin36/APOC-Editor#3]
![apoctor2](https://user-images.githubusercontent.com/11581207/87160952-7927f480-c2cc-11ea-822c-3c6cef9e341a.png)

**Comment by makus82** [comment]
![apoctor2](https://user-images.githubusercontent.com/11581207/87161299-03705880-c2cd-11ea-8fab-644c2aa8d476.png)

**Comment by Atrosha** [comment]
Nice, @makus82 ! But what do you think about "APOC-Editor" not "APOCTOR"?

**Comment by makus82** [comment]
I spoke with the skin and suggested making the name more unique so that it does not get lost in the sea of other editors
if you don’t like it, it can cancel the pull, no problem
